// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://atigmhzjbnrqgkdpreey.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0aWdtaHpqYm5ycWdrZHByZWV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyNTM2MTQsImV4cCI6MjA1NzgyOTYxNH0.KByGLI3S5v1TuVYLNJVT8pYFU2ttVVVCBMUwIH6McsM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);